### ISSUE TITLE
AttributeError: <unknown>.InlineShapes

### ISSUE THREAD

**Issue by ESOSHEN** [ESOSHEN/Python#1]
C:\Users\ESOSHEN\Desktop\test\_hw_txB_10W_analogDohertyPeakAttTab20170606171456.jpgException in Tkinter callbackTraceback (most recent call last):  File "C:\Anaconda3\lib\tkinter\__init__.py", line 1559, in __call__    return self.func(*args)  File "C:/Users/ESOSHEN/Desktop/test/GUIexe.py", line 888, in on_click    plot_1(cmd)  File "C:/Users/ESOSHEN/Desktop/test/GUIexe.py", line 800, in plot_1    pic=sel.InlineShapes.AddPicture(filename)  File "C:\Anaconda3\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__    raise AttributeError("%s.%s" % (self._username_, attr))AttributeError: <unknown>.InlineShapes

**Comment by ESOSHEN** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Anaconda3\lib\tkinter\__init__.py", line 1559, in __call__
    return self.func(*args)
  File "C:/Users/ESOSHEN/Desktop/test/GUIexe.py", line 888, in on_click
    plot_1(cmd)
  File "C:/Users/ESOSHEN/Desktop/test/GUIexe.py", line 800, in plot_1
    pic=sel.InlineShapes.AddPicture(filename)
  File "C:\Anaconda3\lib\site-packages\win32com\client\dynamic.py", line 527, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: <unknown>.InlineShapes
